### ISSUE TITLE
生成的vmess链接在v2rayN客户端导入没反应，应该是最后生成链接的时候的兼容性问题吧?

### ISSUE THREAD

**Issue by goodffd** [phlinhng/v2ray-tcp-tls-web#1]
生成的vmess链接在v2rayN客户端导入没反应，应该是最后生成链接的时候的兼容性问题吧?

**Comment by phlinhng** [comment]
> 生成的vmess链接在v2rayN客户端导入没反应，应该是最后生成链接的时候的兼容性问题吧?

链接内容应该是没问题的，但是目前有个bug是bash在输出的时候会自动将过长内容分行造成复制出错，我再研究看看怎麽修。目前可以先用我写的另一个工具[Shawdowrockets 訂閱鏈接編輯器
](https://www.phlinhng.com/b64-url-editor/)来手动生成链接。

**Comment by phlinhng** [comment]
Fixed.
