### ISSUE TITLE
脚本选项问题

### ISSUE THREAD

**Issue by CyangHH** [phlinhng/v2ray-tcp-tls-web#12]
选项4有问题，无法正确设置CDN，输出结果和选择2一致

**Comment by phlinhng** [comment]
> 选项4有问题，无法正确设置CDN，输出结果和选择2一致

@CyangHH 选择 4 出现两个 vmess 链接代表 CDN 己经开启了，不用再重复设置。选项 4 是设计给初次安装 V2Ray 时没有设置 CDN 的人用的，若初次安装时设置了 CDN，再运行选项 4 会直接显示 vmess 链接。

**Comment by CyangHH** [comment]
了解，感谢！
