### ISSUE TITLE
只需要V2RAY，不需要共存Trojan-go的情况下，是否可以去掉tls-shunt-proxy 分流TLS 

### ISSUE THREAD

**Issue by CyangHH** [phlinhng/v2ray-tcp-tls-web#13]
在跑speedtest,tls-shunt-proxy比较影响性能

**Comment by phlinhng** [comment]
@CyangHH 就算只運行 V2Ray，仍然要靠 tls-shunt-proxy 進行 TCP+TLS+WEB 的證書申請與網站偽裝。tls-shunt-proxy 分流器應該是目前 TCP+TLS+WEB 性能最好，操作最容易的實現了。    
https://guide.v2fly.org/advanced/tcp_tls_shunt_proxy.html

**Comment by phlinhng** [comment]
@CyangHH BBR 開了嗎？

**Comment by phlinhng** [comment]
己协助反馈给上游。
