### ISSUE TITLE
 Package 'gpg' has no installation candidate ?

### ISSUE THREAD

**Issue by joshatt** [phlinhng/v2ray-tcp-tls-web#14]
ubuntu 16.04.

root@ABCD:~# apt update
Hit:1 http://ap-tokyo-1-ad-1.clouds.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:3 http://ap-tokyo-1-ad-1.clouds.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://ap-tokyo-1-ad-1.clouds.archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists... Done                     
Building dependency tree       
Reading state information... Done
3 packages can be upgraded. Run 'apt list --upgradable' to see them.

root@ABCD:~# bash <(curl -sL https://raw.githubusercontent.com/phlinhng/v2ray-tcp-tls-web/master/install.sh) && v2script
Hit:1 http://ap-tokyo-1-ad-1.clouds.archive.ubuntu.com/ubuntu xenial InRelease
Hit:2 http://security.ubuntu.com/ubuntu xenial-security InRelease
Hit:3 http://ap-tokyo-1-ad-1.clouds.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://ap-tokyo-1-ad-1.clouds.archive.ubuntu.com/ubuntu xenial-backports InRelease
Reading package lists...
E: Package 'gpg' has no installation candidate
/dev/fd/63: line 65: jq: command not found

**Comment by phlinhng** [comment]
Thanks for reporting. Seem like installing gpg may cause the whole `apt-get install` process to fail under some circumstance. I've removed the requirement of `gpg` since it's not necessary though. Please reboot and reinstall the script.

**Comment by joshatt** [comment]
After rebooting, everything is perfect. 
Thanks for your help.

~cheers



----- Original Message -----
