### ISSUE TITLE
centos 7.6 安装提示：jq: command not found

### ISSUE THREAD

**Issue by jelly0925** [phlinhng/v2ray-tcp-tls-web#15]
jq: command not found

**Comment by phlinhng** [comment]
centos 要先添加 epel 源才能安裝 jq，可以參考: https://www.cnblogs.com/CaptainLin/p/7064520.html

**Comment by jelly0925** [comment]
谢谢，我试一下呀。

**Comment by jelly0925** [comment]
脚本能不能自动集成对依赖的判断呀。

**Comment by phlinhng** [comment]
> 脚本能不能自动集成对依赖的判断呀。

@jelly0925 其实在 Debian/Ubuntu 上己经将安装依赖集成在 [`install.sh`](https://github.com/phlinhng/v2ray-tcp-tls-web/blob/master/install.sh) 里了。之后 CentOS 也会适配的。

**Comment by phlinhng** [comment]
2.0.2 版腳本已支持 CentOS 7+
```sh
curl -fsSL https://raw.githubusercontent.com/phlinhng/v2ray-tcp-tls-web/vless/src/v2gun.sh -o ~/v2gun.sh && bash ~/v2gun.sh
```
