### ISSUE TITLE
请问使用脚本开启V2RAY的TCP+TLS+WEB，Trojan-go和TG代理后，都需要开放哪些端口？

### ISSUE THREAD

**Issue by LeiD215** [phlinhng/v2ray-tcp-tls-web#17]
请问使用脚本开启V2RAY的TCP+TLS+WEB，Trojan-go和TG代理后，都需要开放哪些端口？

**Comment by phlinhng** [comment]
对外开放 80 和 443 即可。
对内确保 3128 (mtg)、3566 (v2ray 预留)、3567 (tj-go) 不被其他程序占用或阻档。

**Comment by LeiD215** [comment]
谢谢
