### ISSUE TITLE
请教关于生成订阅的问题。

### ISSUE THREAD

**Issue by LeiD215** [phlinhng/v2ray-tcp-tls-web#18]
我有4台VPS，想生成一个订阅便于管理，不需要流量控制这些功能，请问有什么好软件推荐吗？

**Comment by phlinhng** [comment]
可以用我写的另一个工具 [Shawdowrockets 訂閱鏈接編輯器](https://www.phlinhng.com/b64-url-editor/)
如果不想用我的API，把这个工具生成的 BASE64 放到一个纯文本档案里再放到你的服务器或 Github Gist 上也可以达成订阅的效果。

**Comment by LeiD215** [comment]
好的，谢谢。
