### ISSUE TITLE
建议增加对tls版本的设置

### ISSUE THREAD

**Issue by dfliaoyue** [phlinhng/v2ray-tcp-tls-web#19]
默认是tls1.2+tls1.3。但tls1.2在安全性和速度上都逊色于tls1.3。尽管会优先使用tls1.3，但允许tls1.2似乎有被降级探测的风险。
能否加个设置，需要更好兼容性的选tls1.2+tls1.3，对数据隐匿性要求高的选择tls1.3 only？

**Comment by phlinhng** [comment]
可以手动更改 `/etc/tls-shunt-proxy/config.yaml`，将 tls12 去掉即可开启 tls 1.3 only。我个人倾向保持现有的默认值，理由如下
1. 现在纯 TLS 1.3 的网页很少，纯 TLS 1.3 的伪装站 + 大流量可能会增加特征
2. 脚本应该尽量简单，俐落多一个设置会迷惑某些用户
3. 改成 tls1.3 only 只要修改一个文件，有需要的用户手动改一下并不会太难
