### ISSUE TITLE
脚本里缺少ntp服务安装，导致部分机器启动ntp失败

### ISSUE THREAD

**Issue by goodffd** [phlinhng/v2ray-tcp-tls-web#2]
脚本里面有启动ntp服务，但我好几个vps默认都没有安装这个服务，导致ntp启动失败，这个在脚本里需要ntp服务安装吧？另外建议脚本能做成菜单式，1、安装。2、卸载。3、升级v2ray内核。4、生成vmess链接

**Comment by phlinhng** [comment]
ntp己修复。    
做成菜单这个建议不错，会在下个版本加上。

**Comment by phlinhng** [comment]
菜单版脚本己发布(https://github.com/phlinhng/v2ray-tcp-tls-web/releases/tag/v0.1)。目前有安装新三件套(TCP+TLS+WEB)、升级v2Ray内核、生成vmess链接、生成订阅链接五个功能，欢迎试用。

**Comment by goodffd** [comment]
作者有电报么，加个好友呗

**Comment by phlinhng** [comment]
> 作者有电报么，加个好友呗

我的电报没设置ID，你发ID给我我加你呗。

**Comment by goodffd** [comment]
1009697987

**Comment by phlinhng** [comment]
> 1009697987

这个好像加不了

**Comment by goodffd** [comment]
加手机看看，+8613857478677
