### ISSUE TITLE
请教一下关于订阅是否会被爬虫爬到的问题

### ISSUE THREAD

**Issue by LeiD215** [phlinhng/v2ray-tcp-tls-web#20]
请问脚本生成的放到网站目录下的订阅文件，是否会被爬虫爬到？

**Comment by phlinhng** [comment]
1. 脚本会在网站根目录放置`robots.txt`，防止搜索引擎爬虫
2. 网站目录结构不是公开的，爬虫需要知道档名才能爬，订阅文件的档名是16位随机英数字，用于防范大部分的 crawler 应该足够了（一般的爬虫应该不会没事乱爬随机档名）

**Comment by LeiD215** [comment]
好的
