### ISSUE TITLE
请问，想在安装V2RAY，Trojan-go和TG代理后，新增加一个网站，请问需要如何操作？

### ISSUE THREAD

**Issue by LeiD215** [phlinhng/v2ray-tcp-tls-web#21]
正常使用代理后，想新增加一个单独的域名网站和路径，自己试了好几次都失败了，请问应该如何操作？

**Comment by phlinhng** [comment]
如果你的網站是用架在 web 服務器而不是 TLS分流器自身的 fileServer 上，alpn 只能用 http1.1
