### ISSUE TITLE
TCP+TLS 和 WS+CDN 默认全装吗？

### ISSUE THREAD

**Issue by gkeyes** [phlinhng/v2ray-tcp-tls-web#23]
你好，小白想问下，我在安装V2ray的时候开启了CDN，最后生成了两个vmess，其中一个是TCP+TLS 无法连接，WSS+CDN的正常使用，这是正常的吗？

**Comment by phlinhng** [comment]
1. 默认只装 TCP+TLS，CDN 要选择开启才会装
2. Cloudflare 上将你的域名改成 "DNS Only"，应该就能正常使用两个模式了。若问题依旧，请利用 ipip.net 或站长工具的 ping 检测检查 IP 是否被墻。

**Comment by gkeyes** [comment]
> * 默认只装 TCP+TLS，CDN 要选择开启才会装
> * Cloudflare 上将你的域名改成 "DNS Only"，应该就能正常使用两个模式了。若问题依旧，请利用 ipip.net 或站长工具的 ping 检测检查 IP 是否被墻。



> * 默认只装 TCP+TLS，CDN 要选择开启才会装
> * Cloudflare 上将你的域名改成 "DNS Only"，应该就能正常使用两个模式了。若问题依旧，请利用 ipip.net 或站长工具的 ping 检测检查 IP 是否被墻。

谢谢，确实关了CF的代理就两个都可以用，没注意到TCP+tls不支持cloudflare的cdn加速。
解决了，谢谢
