### ISSUE TITLE
关于TCP与WS共存的设置问题

### ISSUE THREAD

**Issue by ylqjgm** [phlinhng/v2ray-tcp-tls-web#24]
我使用OpenWRT进行科学上网，同时安装了TCP+WS+Trojan
其中TCP和WS的域名是aa.ccc.com这样，Trojan为bb.ccc.com
域名解析使用的阿里云，然后CF使用第三方，于是解析记录如下：
aa.ccc.com使用CNAME解析到地址aa.ccc.com.cdn.cloudflare.net
bb.ccc.com使用A解析到VPS
在第三方中，将aa.ccc.com解析到VPS，同时把小云朵关闭

目前，在OpenWRT中，TCP的直接使用链接导入，地址保持为aa.ccc.com，而WS的，链接导入，但地址更改为CF的指定IP
可是现在发现无法科学上网，很奇怪

**Comment by phlinhng** [comment]
就你的描述很难判断是节点还是 OpenWRT 的问题，你先用手机或电脑客户端试试节点能不能连上。

**Comment by ylqjgm** [comment]
现在时好时坏，估计节点有点问题，好像一下能连接，一下不能，移动网络墙中墙

**Comment by ylqjgm** [comment]
多次测试后，发现了问题，是SSL引起的，导致CDN模式无法链接，也就是连网站都打不开
每次访问CDN网址，就提示：

> 建立安全连接失败
> 连接到 aa.ccc.com 时发生错误。无法安全地与对等端通信：没有双方共用的加密算法。
> 错误代码：SSL_ERROR_NO_CYPHER_OVERLAP
>     由于不能验证所收到的数据是否可信，无法显示您想要查看的页面。
>     建议向此网站的管理员反馈这个问题。

CF中已开启完全模式，实在不知道如何解决了

**Comment by phlinhng** [comment]
cf partner 的回源模式似乎和直接用 cf dns 解析不太一樣，您可以換個域名，試試直接將域名的 ns 改到cf 上。

**Comment by ylqjgm** [comment]
> cf partner 的回源模式似乎和直接用 cf dns 解析不太一樣，您可以換個域名，試試直接將域名的 ns 改到 cf 上。

好的，那我试试看

**Comment by ylqjgm** [comment]
已测试了下，经过昨晚一晚上的测试，似乎就是DNS的问题，改为CF后，没有再出现掉线等情况
目前域名已经转为CF做NS服务器，统统指向VPS，然后OpenWRT中再配置指定IP，目前使用一晚上无问题
