### ISSUE TITLE
trojan-go 0.8.0版本发布 配置文件有修改

### ISSUE THREAD

**Issue by wangfeng35** [phlinhng/v2ray-tcp-tls-web#26]
```
https://github.com/p4gefau1t/trojan-go/releases/tag/v0.8.0

Websocket配置略微改动，"hostname”更名为"host"
```

有空就跟进下吧，辛苦了！

**Comment by phlinhng** [comment]
首先，感謝您的支持與鼓勵。這個腳本沒有開啟 trojan-go 的 websocket 模式，配置文件改動應該暫時不影響使用。

**Comment by wangfeng35** [comment]
> 首先，感謝您的支持與鼓勵  這個腳本沒有開啟 trojan-go 的 websocket 模式，配置文件改動應該暫時不影響使用。

原来如此 明白了~
多谢，脚本非常给力！！！
