### ISSUE TITLE
trojan-qt5（windows）使用正常，原版Igniter（安卓）打不开网站

### ISSUE THREAD

**Issue by fwcde** [phlinhng/v2ray-tcp-tls-web#27]
作者您好，感谢分享优秀的作品！

使用您的脚本安装完v2ray和trojan，v2ray使用正常，trojan有点问题，具体现象是：同一WiFi网络环境下，Windows平台trojan-qt5客户端使用正常，但是安卓原版Igniter客户端不能翻墙（使用其他trojan脚本架设则能正常工作），连接服务器后打不开任何网站。

不知是Igniter的问题，还是脚本兼容性问题，希望能解决，盼复，感谢！

**Comment by phlinhng** [comment]
我测试的时候都是用 iOS 的 Shadowrocket 连的，在 iPhone 上表现正常。之前的确有人反映过原版 Ingiter 连不上， 正好我的安卓机最近变砖了 :( 待我买新的安卓机后再测试看看

**Comment by fwcde** [comment]
哈哈，理解。不过还是很期待能够解决此问题，毕竟安卓平台的Trojan客户端没几个，大多数都是用Igniter。

**Comment by fwcde** [comment]
找到原因了！把服务器Trojan-go配置文件里 "router"的enabled改成false就行了。

**Comment by phlinhng** [comment]
竟然还有这个差别 😅 我研究下脚本要怎么改

**Comment by phlinhng** [comment]
默認配置先禁用 router 了。
