### ISSUE TITLE
脚本生成的V2ray分享链接格式不规范，在Trojan-QT5等客户端里导入后无法正常使用

### ISSUE THREAD

**Issue by fwcde** [phlinhng/v2ray-tcp-tls-web#28]
现象：脚本生成的V2RAY（TCP+TLS+WEB）分享链接在v2rayN里导入后使用正常，但是Trojan-QT5里导入后无法正常使用。

原因：分享链接里"net":""未标明传输协议类型，v2rayN默认当作TCP对待，但是Trojan-QT5等客户端严格按照分享链接里的传输协议类型执行，咱链接里的传输协议类型为空，导致错误。

解决办法：把V2RAY（TCP+TLS+WEB）分享链接里的 "net":"" 改为 "net": "tcp" , 希望作者修正，谢谢！

**Comment by phlinhng** [comment]
`net` 为空时默认作为 tcp 没有不规范，v2ray-core 不指定传输层协议时默认也是 tcp 。考量到 v2RayN 是 vmess:// url 的制定者，且此写法在其他客户端也是合法的，个人倾向认为应该是 Trojan-Qt5 要兼容 `net` 为空的写法，

**Comment by fwcde** [comment]
有道理
