### ISSUE TITLE
Telegram proxy fake TLS header change

### ISSUE THREAD

**Issue by hybtoy** [phlinhng/v2ray-tcp-tls-web#29]
Hello,
How To change Fake TLS header for mtg?

1. Generate new secret - mtg generate-secret -c your_domain tls
2. Update v2script.conf
3. Update tls-shunt-proxy
4. Restart tls-shunt-proxy and mtg

Are these steps correct?

**Comment by phlinhng** [comment]
@hybtoy you can modified fake tls sni of mtg by the following steps
1.  `mtg generate-secret -c your_domain tls`
2. edit `/etc/systemd/system/mtg.service`
3.  `systemctl daemon-reload && systemctl restart mtg`
4. edit `/etc/tls-shunt-proxy/config.yaml`
5.  ` systemctl restart tls-shunt-proxy`
6. (optional) edit `/usr/local/etc/v2script/config.json`

**Comment by hybtoy** [comment]
@phlinhng 
Can I use my trojan domain name as Fake TLS header?
Thanks.

**Comment by phlinhng** [comment]
@hybtoy no (and why?) Trojan-go and mtg are both `default` traffic and each vhost only support one default. If you insist to do so, try to make trojan-go work in websocket mode and put trojan-go in `http`  to make room for mtg (which is not supported by this script, you have to figure it out by  yourself).
