### ISSUE TITLE
大佬，脚本怎么修改反代地址

### ISSUE THREAD

**Issue by laobanbiefangcu** [phlinhng/v2ray-tcp-tls-web#30]
非常感谢！

**Comment by phlinhng** [comment]
@laobanbiefangcu 不卸载，直接重新运行一次脚本重新安装一遍。

**Comment by laobanbiefangcu** [comment]
> @laobanbiefangcu 不卸载，直接重新运行一次脚本重新安装一遍。

大佬我可能没讲明白，是安装好之后，怎么换伪装网站

**Comment by laobanbiefangcu** [comment]
/var/www/html

找到了，感谢！
