### ISSUE TITLE
期待支持VLESS

### ISSUE THREAD

**Issue by dfliaoyue** [phlinhng/v2ray-tcp-tls-web#37]
新版的v2ray-core已经支持VLESS了，希望这个脚本能支持一键配置VLESS+TCP+WEB

**Comment by phlinhng** [comment]
可以安排

**Comment by phlinhng** [comment]
鑑於 VLESS 和 TLS分流器對 VLESS 的支持目前還不夠完善，這個月內應該不會推出 VLESS 三合一腳本。有搭建 VLESS 需求的可以參考 [vless-nginx](https://github.com/phlinhng/vless-nginx)

**Comment by phlinhng** [comment]
新版本已支持 VLESS，歡迎使用。
```sh
curl -fsSL https://raw.githubusercontent.com/phlinhng/v2ray-tcp-tls-web/vless/src/v2gun.sh -o ~/v2gun.sh && bash ~/v2gun.sh
```
