### ISSUE TITLE
how to change amp.cloudfalre.com for other url ?

### ISSUE THREAD

**Issue by ingnelson** [phlinhng/v2ray-tcp-tls-web#42]
Hello.

can you tell me how to change the url `amp.cloudflare.com`  for other website ?

can you give me the directories files that i have to change , please ?

i want to use other websites example : 
alfa.gob.mx instead amp.cloudflare.com

i will wait your reply.

**Comment by ColderCoder** [comment]
It's completely client-side. Change it directly to any site using Cloudflare CDN or simply Cloudflare IP (e.g. 1.0.0.1).

**Comment by ingnelson** [comment]
@phlinhng @ColderCoder 
Could you explain a little more , please ? 
Do I need to configure a specific DNS record ?
Inside your project I see that the configuration works only  if I use any of this 2 domains : amp.cloudflare.com www.digitalocean.com

How to configure it to add any other website and not a subdomain ?

Could you explain , please or give the commands or at least screenshots ?

**Comment by ColderCoder** [comment]
> @phlinhng @ColderCoder
> Could you explain a little more , please ?
> Do I need to configure a specific DNS record ?
> Inside your project I see that the configuration works only if I use any of this 2 domains : amp.cloudflare.com [www.digitalocean.com](http://www.digitalocean.com)
> 
> How to configure it to add any other website and not a subdomain ?
> 
> Could you explain , please or give the commands or at least screenshots ?

No need to. Any domain using Cloudflare CDN will do. icook.tw for example. And any Cloudflare IP is acceptable (e.g. 1.0.0.1). If you just want a pretty domain of your own, add an A record and get CDN enabled so that you can use it. It may not improve your experience though. 

For better experience, you can check your ping & package loss & speed to Cloudflare IPs and select the best one.

**Comment by phlinhng** [comment]
Just modified client-side configurations by yourself and you will get it. https://github.com/phlinhng/v2ray-tcp-tls-web/issues/31
