### ISSUE TITLE
更新v2ray core后连接失败

### ISSUE THREAD

**Issue by waitandsoon** [phlinhng/v2ray-tcp-tls-web#50]
如题，必须卸载后安装才可以。
v2ray如果直接更新，会启动失败。

**Comment by waitandsoon** [comment]
LOG如下：
Sep 19 17:15:19 abc systemd[1]: v2ray.service: Main process exited, code=exited, status=255/EXCE
Sep 19 17:15:19 abc systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 19 17:15:19 abc systemd[1]: v2ray.service: Service RestartSec=100ms expired, scheduling rest
Sep 19 17:15:19 abc systemd[1]: v2ray.service: Scheduled restart job, restart counter is at 5.
Sep 19 17:15:19 abc systemd[1]: Stopped V2Ray Service.
Sep 19 17:15:19 abc systemd[1]: v2ray.service: Start request repeated too quickly.
Sep 19 17:15:19 abc systemd[1]: v2ray.service: Failed with result 'exit-code'.
Sep 19 17:15:19 abc systemd[1]: Failed to start V2Ray Service.

**Comment by lkxztc** [comment]
我也是和你一个情况，可能是脚本哪里有问题，希望能尽快修复吧，不然更新一次核心就得重装一次，太麻烦了。

**Comment by phlinhng** [comment]
已修复，现在每次更新后会重建 `v2ray.service` 避免重启失败。
