### ISSUE TITLE
未更新script情况下链接失败

### ISSUE THREAD

**Issue by sportfit** [phlinhng/v2ray-tcp-tls-web#51]
v2 tcp tls script安装使用有些日子了，但近期tcp tls突然无法正常连接，登录服务器查看状态是caddy service删除了，而同时安装之trojan go却正常，奇怪我未更新脚本情况下，数据处理应为本地执行，怎么会参与外部连接继而数据交换。使得脚本无法正常运行呢？

**Comment by phlinhng** [comment]
caddy 只處理網頁，不影響 v2ray。vmess 不能用可能是你客戶端更新了，服務端還是舊版。試試把客戶端 aid 和服務端 aid 都設成 2 看看。
