### ISSUE TITLE
Trojan-go现在还在维护吗？

### ISSUE THREAD

**Issue by chpos** [phlinhng/v2ray-tcp-tls-web#54]
我平时主要使用脚本中的Trojan-go，我记得我夏天部署的时候Trojan-go 的版本是 0.82，我今天重新部署了一下发现版本也是0.82，问一下作者，Trojan-go还在维护吗？

**Comment by phlinhng** [comment]
1. Trojan-Go 最新版本請見 [Release](https://github.com/p4gefau1t/trojan-go/releases)
2. Trojan-Go 作者表示現在沒有什麼新功能要加了，主要以修 Bug 為主，所以現在更新比較慢
3. 作者上次更新是 18 天前，那會已經入秋了

**Comment by chpos** [comment]
谢谢！
