### ISSUE TITLE
未启用cdn功能时，生成的vmess链接域名被/custom/cf_node中icook.tw替代，而不是用户输入的域名。

### ISSUE THREAD

**Issue by fwcde** [phlinhng/v2ray-tcp-tls-web#56]
BUG复现步骤：

假设我的域名是aaa.bbb.com，域名直接解析至运行脚本的vps，没有使用cdn。

运行脚本，输入域名aaa.bbb.com，结果脚本生成的vmess链接是vmess://****@icook.tw:443/path=***，而不是vmess://****@aaa.bbb.com:443/path=***，将该键接导入v2ray客户端后无法正常工作。

BUG原因：使用/custom/cf_node的逻辑有问题，盼望改进。

**Comment by phlinhng** [comment]
如果你的域名 DNS 沒有托管在 Cloudflare 上，生成的 Vmess 鏈接對你來說就是沒有用的。請使用 VLESS 或 Trojan 直連，當然，執意要使用 VMess + WSS 方式直連的話，你自己替換一下地址也是可以用的。

**Comment by fwcde** [comment]
作者本意是要将伪装host字段改成icook.tw吧？你现在改的是adress-_-!

**Comment by phlinhng** [comment]
請先把 www.v2fly.org 讀完，並學習一下何謂 Header、何謂 SNI，再來談「問題」。

**Comment by phlinhng** [comment]
> 作者本意是要将伪装host字段改成icook.tw吧？你现在改的是adress-_-!

改 address 是對的，`icook.tw` 只是用來解析出 CF 的節點，實際上仍會回源到 Host 指定的地址裡。細節在 #31 解釋過了。

**Comment by fwcde** [comment]
统一用icook.tw这种小众域名，不怕被GFW盯上吗？

**Comment by phlinhng** [comment]
那是我從 IBMYes 裡面抄過來的，之後會推出功能讓用戶更換成其他節點（例如 amp.cloudflare.com, www.digitalocean.com, www.garmin.com, 1.0.0.0 等）。

**Comment by fwcde** [comment]
感谢作者辛勤付出，我没有抬杠的意思。只是我之前把你脚本推荐给小白朋友们使用，生成的链接adress有误连不上，对小白们体验不好。

**Comment by fwcde** [comment]
毕竟小白们不用cdn

**Comment by fwcde** [comment]
使用脚本的大多数是小白，大神能够兼顾小白，无需二次修改链接。尤其是vmess旧版链接格式，小白们未必知道base64解码修改后再编码。

**Comment by phlinhng** [comment]
> 使用脚本的大多数是小白，希望大神能够兼顾小白，无需他们再去修改链接，尤其是vmess旧版链接格式，小白们未必知道base64解码修改后再编码。

待之後 VLESS 分享標準出台這都不是問題。寫這個腳本是為了推廣 VLESS，留著 VMess 是為了兼容用的。我只負責把腳本寫好，教育小白是博主和油管主的事。如果有些所謂小白還巴著 VMess WSS 不放，GitHub 上有很多優秀的同類腳本可以選擇，不一定要用我的。

**Comment by phlinhng** [comment]
VMess 默認 CDN 是有用意的，就是要讓直連用戶用 VLESS 和 Trojan 直連，若用戶的線路直連太差，才借用 Cloudflare 回源行為中轉。如果有些所謂小白買了什麼年付 0.99 越南盾的垃圾 VPS，就算 VMess WSS 直連可以通也不要肖想有什麼使用體驗。
