### ISSUE TITLE
web站点好像打不开

### ISSUE THREAD

**Issue by dfliaoyue** [phlinhng/v2ray-tcp-tls-web#6]
直接输入网址没有站点，在/var/www/html里放入网站模板后也没用。但v2ray功能可用。
设置：vultr debian 10 主机，安装bbr原版（内核5.6），安装tcp+tls+web三件套。

**Comment by phlinhng** [comment]
可能是docker没有安装成功或是caddy没有启动，方便提供一下你输入`docker ps -a`后输出的信息吗？

试着在网址前加上https应该看得到站点

On May 23, 2020, at 5:43 PM, dfliaoyue <notifications@github.com> wrote:

直接输入网址没有站点，在/var/www/html里放入网站模板后也没用。但v2ray功能可用。
设置：vultr debian 10 主机，安装bbr原版（内核5.6），安装tcp+tls+web三件套。

**Comment by dfliaoyue** [comment]
> 可能是 docker 没有安装成功或是 caddy 没有启动，方便提供一下你输入 docker ps -a 后输出的信息吗？ 试着在网址前加上 https 应该看得到站点

解决！加上https就好了！非常感谢！【不知为何按照官方流程就是连不上，很感谢你的脚本！】
