### ISSUE TITLE
nginx https 允许IP访问，暴露证书

### ISSUE THREAD

**Issue by CyangHH** [phlinhng/v2ray-tcp-tls-web#61]
以前的版本访问https://<IP> 会返回一个404，现在返回默认站点证书，尝试了修改了下http倒是可以禁止IP访问，https好像不行，请问要如何修改才可以禁止https IP访问，避免暴露证书，另外我看了下nginx.config 好像并没有监听443端口，

**Comment by phlinhng** [comment]
以前版本的 HTTP 回落路線是：`vless@v2ray-core -> trojan-go -> nginx`，新版本的路線是 `vless@v2ray-core -> trojan@v2ray-core -> nginx`。所以問題可能出在 v2ray-core 的 trojan 實現上，不過我剛才看翻了 V2Ray 的文檔沒發現怎麼改。你可以到 [@v2fly/v2ray-core](https://github.com/v2fly/v2ray-core) 提個 issue。

**Comment by phlinhng** [comment]
還有個曲線救國的方式是讓 nginx 前置監听 443，v2ray-core 放在後面。

**Comment by CyangHH** [comment]
感谢解答，thanks！

**Comment by phlinhng** [comment]
經測試，現在 xray-core 默認會拒絕純 IP 的 TLS 握手，因此不會暴露證書。
