### ISSUE TITLE
Trojan-go地址识别问题

### ISSUE THREAD

**Issue by blue2018** [phlinhng/v2ray-tcp-tls-web#64]
phlinhng，你好！用脚本生成的Trojan-go链接，Trojan-Qt5和Igniter-Go客户端均无法通过剪切板url的方式导入生成配置，请问该如何操作呢？谢谢

**Comment by phlinhng** [comment]
感謝回報，已經加了修復，請更新腳本後運行 "4) 显示链接"。
https://github.com/phlinhng/v2ray-tcp-tls-web/blob/dfcf1f3d17363be5f4f182d376fe005fc63ed886/src/v2gun.sh#L201-L202

**Comment by blue2018** [comment]
好的，谢谢！

> 感謝回報，已經加了修復，請更新腳本後運行 "4) 显示链接"。
> https://github.com/phlinhng/v2ray-tcp-tls-web/blob/dfcf1f3d17363be5f4f182d376fe005fc63ed886/src/v2gun.sh#L201-L202

**Comment by blue2018** [comment]
刚测试了，貌似还是不行喔，我已经重新安装脚本了 

> > 感謝回報，已經加了修復，請更新腳本後運行 "4) 显示链接"。
> > https://github.com/phlinhng/v2ray-tcp-tls-web/blob/dfcf1f3d17363be5f4f182d376fe005fc63ed886/src/v2gun.sh#L201-L202
