### ISSUE TITLE
使用自定义 Cloudflare 节点无法上网

### ISSUE THREAD

**Issue by zing518** [phlinhng/v2ray-tcp-tls-web#65]
使用自定义 Cloudflare 节点无法上网 。哪里错？谢谢

**Comment by phlinhng** [comment]
自定義 Cloudflare 節點功能要求域名以 DNS 方式接入 Cloudflare， CF Partner 無法使用。

**Comment by zing518** [comment]
> 自定义Cloudflare，以DNS方式接受Cloudflare，CF合作伙伴无法使用。
嗯 谢谢！上次用的是腾讯dns 解析
