### ISSUE TITLE
debian 10 的系统貌似域名证书签发有问题，换成debian 9 就正常了。

### ISSUE THREAD

**Issue by iJayscn** [phlinhng/v2ray-tcp-tls-web#67]
不知是不是 有些玄学？

**Comment by xhrzg2017** [comment]
建议作者添加第二种证书添加方法 指定路径识别。因为ssl签名文件验证要配置nginx比较麻烦，dns可以一年有效期
https://freessl.cn/已经验证了，我认为没必要再次签发。

**Comment by phlinhng** [comment]
今天更新的版本已经优化证书申请流程，现在应该不会再申请失败了。
如果想用自己的证书，待脚本成功申请证书后，再将 `/etc/ssl/v2ray/key.pem` 和 `/etc/ssl/v2ray/fullchain.pem` 换成自己的证书并停用 acme.sh 自动 renew 即可。
停用自动 renew 的指令如下:
```
acme.sh --remove -d example.com --ecc
```
之后版本会加入事先指定证书的功能，只要存在证书档案就不会进行申请。
