### ISSUE TITLE
trojan-go 部分安装失败

### ISSUE THREAD

**Issue by zyaowei** [phlinhng/v2ray-tcp-tls-web#68]
选择操作 [输入任意值退出]: 6
trojan-go is not installed. start installation
Getting the latest version of trojan-go
v0.8.2
trojan-go.zip     100%[===========>]   6.41M  1.15MB/s    in 7.1s    
/root/v2gun.sh: line 245:/usr/bin/chmod: No such file or directory
Building trojan-go.service
trojan-go is installed.
继续其他操作 (yes/no)? n

**Comment by zyaowei** [comment]
显示错误的是245行。
最后安装完成后，依然是有trojan-go的链接，不过连不上。

**Comment by phlinhng** [comment]
这就很奇怪了，我刚才试了一下无法复现问题。你可以确认一下 `/usr/bin/trojan-go` 这个文件存在么？

**Comment by phlinhng** [comment]
如果是全新安装的话，应该先选择 `1) 安装 VLESS + VMess + Trojan + NaiveProxy` 才对哦。

**Comment by blue2018** [comment]
选择操作 [输入任意值退出]: 6
trojan-go is not installed. start installation
Getting the latest version of trojan-go
v0.8.2
trojan-go.zip               100%[=========================================>]   6.41M  7.20MB/s    in 0.9s
/root/v2gun.sh: line 279:/usr/bin/chmod: No such file or directory
Building trojan-go.service
trojan-go is installed.
继续其他操作 (yes/no)? yes

把服务器重置后重新安装了今天发布的新版，可选择“6) 更新 trojan-go”时，依旧提示trojan-go未安装，而且用trojan-go安卓客户端，只要开启了WebSocket就无法链接。

**Comment by zyaowei** [comment]
确实装不上，重新安装也一样。我的显示245行错误。
而且trojan本身不开ws也连接不上。
目前这个讨论已经被关闭，没有解决办法。

**Comment by phlinhng** [comment]
感谢二位的回报，已于 https://github.com/phlinhng/v2ray-tcp-tls-web/commit/fed71b8aa5f1fac4d9f98f2add6763c21cfdf9f4 修复 Trojan-Go 安装问题。

**Comment by zyaowei** [comment]
多谢您的回答。更新后的脚本重装，状态如下：
1.新装的时候没有安装错误的提示。
2.trojan-go更新时候，依然提示未安装，279行报错，同上方报错信息一样。
3.更新之后可以连通，正常上网，不过网速有点慢。（相对于其他同配置同机房的主机）
4.qv2ray的日志查询，有如下报错信息：（其实只有一条错误提示，一直重复）

[INFO]  2020/11/18 11:46:28 socks new udp session from 127.0.0.1:63005
[ERROR] 2020/11/18 11:46:29 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:142 failed to parse udp packet addr | unable to read ATYP | EOF
[INFO]  2020/11/18 11:46:29 connection to UDP_CONN:0 closed sent: 61 B recv: 0 B
[INFO]  2020/11/18 11:46:29 socks udp session closed
[ERROR] 2020/11/18 11:46:30 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:142 failed to parse udp packet addr | unable to read ATYP | EOF
[INFO]  2020/11/18 11:46:30 connection to UDP_CONN:0 closed sent: 61 B recv: 0 B
[INFO]  2020/11/18 11:46:30 socks udp session closed
[INFO]  2020/11/18 11:46:31 socks connection from 127.0.0.1:50837 metadata 8.8.4.4:53
[INFO]  2020/11/18 11:46:31 socks new udp session from 127.0.0.1:63007
[INFO]  2020/11/18 11:46:32 socks connection from 127.0.0.1:50840 metadata 8.8.8.8:53
[INFO]  2020/11/18 11:46:32 socks new udp session from 127.0.0.1:63008
[ERROR] 2020/11/18 11:46:33 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:142 failed to parse udp packet addr | unable to read ATYP | EOF
[INFO]  2020/11/18 11:46:33 connection to UDP_CONN:0 closed sent: 61 B recv: 0 B
[INFO]  2020/11/18 11:46:33 socks udp session closed
[INFO]  2020/11/18 11:46:33 socks connection from 127.0.0.1:50843 metadata 1.1.1.1:53
[INFO]  2020/11/18 11:46:33 socks new udp session from 127.0.0.1:49825
[ERROR] 2020/11/18 11:46:34 github.com/p4gefau1t/trojan-go/proxy.(*Proxy).relayPacketLoop.func1.1:proxy.go:142 failed to parse udp packet addr | unable to read ATYP | EOF
[INFO]  2020/11/18 11:46:34 connection to UDP_CONN:0 closed sent: 61 B recv: 0 B
[INFO]  2020/11/18 11:46:34 socks udp session closed

**Comment by phlinhng** [comment]
trojan-go 已安裝卻識別成未安裝問題 和 chmod 報錯問題已解決 (https://github.com/phlinhng/v2ray-tcp-tls-web/commit/645f90d8ff24152aa8c9b0bf2b9e5c297974f596)
網速慢與 Trojan-Go 是否安裝無關，請確認 BBR 已安裝或開啟，並檢查您本地到服務器的路由是否順暢

**Comment by zyaowei** [comment]
非常感谢您的耐心解答。这个脚本基本上是目前能找到的最完美的脚本了。
