### ISSUE TITLE
安装运行良好

### ISSUE THREAD

**Issue by sportfit** [phlinhng/v2ray-tcp-tls-web#7]
第一次用tcp+tls+web，安装运行良好，新3套太棒了，比另一种ws+tls+web简便多了，谢谢大佬！试用加速内核bbr5.x不敌bbr plus，稳定性不好，速率上下差异较大，可能因机而异吧。

**Comment by phlinhng** [comment]
> 第一次用tcp+tls+web，安装运行良好，新3套太棒了，比另一种ws+tls+web简便多了，谢谢大佬！试用加速内核bbr5.x不敌bbr plus，稳定性不好，速率上下差异较大，可能因机而异吧。

感谢您的肯定与回报！目前测试结果显示，BBRPlus 初期速度胜过 BBR 5.5，经过一阵子后下降然后被 BBR 5.5 超越。BBRPlus 4.14 适合突发小流量 / 档案的场景，BBR 5.5 适合中长期/大档案的场景，可依需求自行选择。
