### ISSUE TITLE
安裝失敗

### ISSUE THREAD

**Issue by chenqiuhe** [phlinhng/v2ray-tcp-tls-web#70]
在谷哥雲前幾天安裝，都顯示證書申請失敗。今天再試，顯示谷歌雲連不上github的服務器失敗？

另外安裝的時候的輸入完域名xxx.cf或www.xxx.cf的域名都顯示ping unknown host, 而直接用ping命令，谷哥雲是正常ping得到的。

**Comment by phlinhng** [comment]
1. 你 ping 的是域名還是 IP? GCP 的 80 端口和 443 端口放行了嗎？
2. xxx.cf 和 www.xxx.cf 代表的是不同的解析，請確認解析是否正確

**Comment by chenqiuhe** [comment]
> 1. 你 ping 的是域名還是 IP? GCP 的 80 端口和 443 端口放行了嗎？
> 2. xxx.cf 和 [www.xxx.cf](http://www.xxx.cf) 代表的是不同的解析，請確認解析是否正確

ping的域名，xxx是我的用戶名這裏用xxx代替
我之前已經搭好了一個實例，前幾天想創多一個日本的備用，用同一命令，失敗了。另一個實例正常使用，不會有防火牆設置問題

**Comment by chenqiuhe** [comment]
![Screenshot_2020-11-18-01-45-32-044_com android chrome](https://user-images.githubusercontent.com/74617338/99427037-da796780-293f-11eb-990c-0a74c90d5110.jpg)

**Comment by chenqiuhe** [comment]
![Screenshot_2020-11-18-01-47-40-817_com android chrome](https://user-images.githubusercontent.com/74617338/99427202-14e30480-2940-11eb-9c72-580d073599bd.jpg)

**Comment by phlinhng** [comment]
換成 Ubuntu 應該就正常了，我會再找時間測試 CentOS 的使用情況，感謝您的回報！
若您急用而本腳本一直安裝失敗的話，歡迎選用 [v2ray-agent](https://github.com/mack-a/v2ray-agent) 這個腳本，造成不便敬請見諒。

**Comment by chenqiuhe** [comment]
> 換成 Ubuntu 應該就正常了，我會再找時間測試 CentOS 的使用情況，感謝您的回報！
> 若您急用而本腳本一直安裝失敗的話，歡迎選用 [v2ray-agent](https://github.com/mack-a/v2ray-agent) 這個腳本，造成不便敬請見諒。

https://github.com/acmesh-official/acme.sh/archive/mast 
er.tar.gz
