### ISSUE TITLE
v2ray 4.33?

### ISSUE THREAD

**Issue by aeroweb340** [phlinhng/v2ray-tcp-tls-web#72]
Hi,

Just upgraded to v2ray 4.33. Nothing works anymore? Went back to the previous version. Is there something we should modifify? (automated script v2.1.2)

**Comment by phlinhng** [comment]
@aeroweb340 As I had mentioned in [v2.1.5](https://github.com/phlinhng/v2ray-tcp-tls-web/releases/tag/v2.1.5) (only available in Mandarin, sorry), since XTLS features will be v2fly release from v2ray-core v4.33+, you have to modify XTLS-related settings in `/usr/local/etc/v2ray/05_inbounds_vless.json` back to TLS to make v2ray work once you choice to update v2ray-core.

**Comment by aeroweb340** [comment]
OK Thanks for your help. I'll give it a try.

**Comment by aeroweb340** [comment]
Sorry to bother again but what do you modify in order to make it work again with v2ray core 4.33 ?
{
  "inbounds": [
    {
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            "id": "",
            "flow": "xtls-rprx-origin"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 3564
          },
          {
            "path": "/fec6f8cc7f114e909",
            "dest": 3565,
            "xver": 1
          },
          {
            "path": "/fec6f8cc7f114e909ws",
            "dest": 3566,
            "xver": 1
          },
          {
            "path": "/fec6f8cc7f114e909wss",
            "dest": 3567,
            "xver": 1
          },
          {
            "path": "/fec6f8cc7f114e909tj",
            "dest": 3568,
            "xver": 1
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "xtls",
        "xtlsSettings": {
          "alpn": [ "http/1.1" ],
          "certificates": [
            {
              "certificateFile": "/etc/ssl/v2ray/fullchain.pem",
              "keyFile": "/etc/ssl/v2ray/key.pem"
            }
          ]
        }
      },
      "sniffing": {
        "enabled": true,
        "destOverride": [ "http", "tls" ]
      },
      "tag": ""
    }
  ]
}
