### ISSUE TITLE
域名实际签发成功了，但是脚本显示失败

### ISSUE THREAD

**Issue by iJayscn** [phlinhng/v2ray-tcp-tls-web#75]
Issuing certificate
[Mon Dec  7 05:54:28 EST 2020] Domains not changed.
[Mon Dec  7 05:54:28 EST 2020] Skip, Next renewal time is: Fri Feb  5 10:54:27 UTC 2021
[Mon Dec  7 05:54:28 EST 2020] Add '--force' to force to renew.
Installing certificate
[Mon Dec  7 05:54:28 EST 2020] Installing key to:/etc/ssl/v2ray/key.pem
[Mon Dec  7 05:54:28 EST 2020] Installing full chain to:/etc/ssl/v2ray/fullchain.pem
[Mon Dec  7 05:54:28 EST 2020] Run reload cmd: chmod 644 /etc/ssl/v2ray/fullchain.pem; chmod 644 /etc/ssl/v2ray/key.pem; systemctl restart v2ray
[Mon Dec  7 05:54:28 EST 2020] Reload success
证书签发失败, 请重试

网页和V2ray都可以正常使用

**Comment by phlinhng** [comment]
感謝回報，已經修正了。
