### ISSUE TITLE
Vmess url configuration do not work

### ISSUE THREAD

**Issue by ingnelson** [phlinhng/v2ray-tcp-tls-web#8]
Hi.
I just install it on Ubuntu 16 vps , but when I try to import the vmess url configuration on my Android v2ray app it doesn't import the file via clipboard and fail .

vmess://eyJhZGQiOiJ3d3cubW92aXN0YXIuY29tLm5pLnp0ZWNsYXJvLnRrIiwiYWlkIjoiMCIsImhvc3QiOiIiLCJpZCI6ImMxMTgzY2UzLWVkZjgtNDAwZi04NmYzLTU5ZTViODRjZGYxZCIsIm5ldCI6IiIsInBhdGgiOiIiLCJwb3J0IjoiNDQzIiwicHMiOiJ3d3cubW92aXN0YXIuY29tLm5pLnp0ZWNsYXJvLnRrOjQ0MyIsInRscyI6InRscyIsInR5cGUiOiJub25lIiwidiI6IjIifQ==

Can you check it ?

**Comment by phlinhng** [comment]
Your link works fine for me. Make sure to copy it correctly in single line without linebreaks and whitespaces.
