### ISSUE TITLE
wss+cdn stable

### ISSUE THREAD

**Issue by sportfit** [phlinhng/v2ray-tcp-tls-web#9]
5/26安装tcp+tls已稳定运行，dns解析服务在cloudflare，手误点开了云朵，vps ip短短数十秒就变为cloudflare ip.,且链接网站正常，但也没多久就自动变回去，云朵自动变灰色。意外的是大佬最新脚本支持wss+cdn与之共存，it's nice!  重新更新脚本后，手动设置cdn，稳定运行，great!

**Comment by phlinhng** [comment]
感谢您的支持 👍
